### ISSUE TITLE
NoMethodError: undefined method `assets' for Rails enginer

### ISSUE THREAD

**Issue by aditya-citrix** [thoughtbot/bourbon#1102]
After upgrading to bourbon 7.0.0 with rails 6.0.3.3 getting this error
```

06:03:43 workers.1     | 2020-09-10T06:03:43.643Z pid=16842 tid=82wdq WARN: NoMethodError: undefined method `assets' for #<Rails::Engine::Configuration:0x0000000002b91f70>
06:03:43 workers.1     | 2020-09-10T06:03:43.643Z pid=16842 tid=82wdq WARN: /home/vagrant/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/railtie/configuration.rb:96:in `method_missing'
06:03:43 workers.1     | /home/vagrant/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bourbon-7.0.0/lib/bourbon.rb:6:in `<class:Engine>'
```

**Comment by AlfonsoUceda** [comment]
I have this problem from time to time, could be fixed by https://github.com/thoughtbot/bourbon/pull/1109/files ?

**Comment by someonewithpc** [comment]
Same problem here

**Comment by saturnflyer** [comment]
#1109 was merged
