### ISSUE TITLE
Support for Rails 7

### ISSUE THREAD

**Issue by Overload119** [thoughtbot/bourbon#1112]
## Description

Is Rails 7 supported? I have the follow error.

<details>

spring rails s
Traceback (most recent call last):
	44: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `<main>'
	43: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `eval'
	42: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/bin/spring:23:in `<main>'
	41: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/bin/spring:23:in `load'
	40: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/spring-3.0.0/bin/spring:49:in `<top (required)>'
	39: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/spring-3.0.0/lib/spring/client.rb:30:in `run'
	38: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/spring-3.0.0/lib/spring/client/command.rb:7:in `call'
	37: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/spring-3.0.0/lib/spring/client/rails.rb:28:in `call'
	36: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/spring-3.0.0/lib/spring/client/rails.rb:28:in `load'
	35: from /Users/amirsharif/Projects/sendapostcardonline/bin/rails:5:in `<top (required)>'
	34: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	33: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	32: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	31: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	30: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	29: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<main>'
	28: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
	27: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
	26: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	25: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	24: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	23: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/railties-7.0.2.3/lib/rails/commands/server/server_command.rb:134:in `perform'
	22: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/railties-7.0.2.3/lib/rails/commands/server/server_command.rb:134:in `tap'
	21: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/railties-7.0.2.3/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	20: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	19: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	18: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	17: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	16: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	15: from /Users/amirsharif/Projects/sendapostcardonline/config/application.rb:8:in `<main>'
	14: from /Users/amirsharif/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler.rb:174:in `require'
	13: from /Users/amirsharif/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
	12: from /Users/amirsharif/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
	11: from /Users/amirsharif/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
	10: from /Users/amirsharif/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
	 9: from /Users/amirsharif/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
	 8: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 7: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 6: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 5: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 4: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 3: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bourbon-7.2.0/lib/bourbon.rb:3:in `<main>'
	 2: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bourbon-7.2.0/lib/bourbon.rb:5:in `<module:Bourbon>'
	 1: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/bourbon-7.2.0/lib/bourbon.rb:6:in `<class:Engine>'
/Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/railties-7.0.2.3/lib/rails/railtie/configuration.rb:96:in `method_missing': undefined method `assets' for #<Rails::Engine::Configuration:0x00007fafa2992948> (NoMethodError)

</details>

## Steps to Reproduce

1. Use Rails 7.0.2.3
2. bundle update
3. Error on Rails startup

## Development Environment

- Bourbon version: 7.2.0
- Platform: Mac OSX

**Comment by Overload119** [comment]
I added `require 'sprockets/railtie'` to `application.rb` and that seemed to do the trick.
