### ISSUE TITLE
Missing dependency: postcss-selector-parser

### ISSUE THREAD

**Issue by DevNIX** [thoughtbot/bourbon#868]
I don't know if it makes sense. I'm using Laravel Elixir.

If I try to execute `@include background(linear-gradient(red, green) left repeat)` the compilation will fail with this message:
```
[10:57:31] 'sass' errored after 994 ms
[10:57:31] Error: Cannot find module 'postcss-selector-parser'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\desarrollo\Development\tpv-entradas\src\node_modules\laravel-elixir\node_modules\gulp-cssnano\node_modules\cssnano\node_modules\postcss-minify-selectors\dist\index.js:19:30)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
[10:57:31] Error in plugin 'run-sequence'
Message:
    An error occured in task 'sass'.
[10:57:31] Finished 'default' after 1.04 s
```

Which gets fixed if I do a `npm install --save postcss-selector-parser`

**Comment by tysongach** [comment]
@DevNIX Hi! It looks like `cssnano` [requires `postcss-minify-selectors`](https://github.com/ben-eb/cssnano/blob/master/package.json#L43). I’m unsure why it didn’t automatically install, as it is listed as a dependency in `cssnano`, but maybe the install failed for some reason.
